CREATE TABLE IF NOT EXISTS "team_appearance" (
  "team_id" TEXT,
  "game_id" TEXT, 
  "home" INTEGER,
  "league_id" TEXT,
  "score" INTEGER,
  "line_score" TEXT,
  "at_bats" REAL,
  "hits" REAL,
  "doubles" REAL,
  "triples" REAL,
  "homeruns" REAL,
  "rbi" REAL,
  "sacrifice_hits" REAL,
  "sacrifice_flies" REAL,
  "hit_by_pitch" REAL,
  "walks" REAL,
  "intentional_walks" REAL,
  "strikeouts" REAL,
  "stolen_bases" REAL,
  "caught_stealing" REAL,
  "grounded_into_double" REAL,
  "first_catcher_interference" REAL,
  "left_on_base" REAL,
  "pitchers_used" REAL,
  "individual_earned_runs" REAL,
  "team_earned_runs" REAL,
  "wild_pitches" REAL,
  "balks" REAL,
  "putouts" REAL,
  "assists" REAL,
  "errors" REAL,
  "passed_balls" REAL,
  "double_plays" REAL,
  "triple_plays" REAL,
  PRIMARY KEY (team_id, game_id),
  FOREIGN KEY (league_id) REFERENCES league(league_id),
  FOREIGN KEY (team_id) REFERENCES team(team_id),
  FOREIGN KEY (game_id) REFERENCES game(game_id));
